### ISSUE TITLE
Add Reading List

### ISSUE THREAD

**Issue by thamilthedal** [scst-cell-iitb/scst-cell-iitb#1]
Library for SC/ST Cell

Must Buy:

Annihilation of caste - Dr. Ambedkar (multiple copies)
Waiting for Visa - Dr. Ambedkar
Revolution and Counter Revolution in India - Dr. Ambedkar
Dr. Babasaheb Ambedkar, Writings and Speeches
Coming Out as Dalit: A Memoir - Yashica Dutt
Caste matters - Suraj yengde
Why I hid my caste - Baburao bagul
Jhoothan - Om prakash Valmiki, 
A weave of my life - A Dalit women memoirs by Urmila Pawar
Slavery - Jotirao Phule
Seeking begumpura - Gail Omvedt
Merit of Caste - Ajanta Subramanium

Optional Buy:

'Akkarmashi' by Tulsidas
biographies of Phule ravidas and Babu jagjevan kushwaha.
Sarvajanik Satya Dharma by Phule
Why were women enslaved Thanthai Periyar
"The Language of the Gods in the World of Men"
"Towards a Political Philology: D. D. Kosambi and Sanskrit"
Cosmopolitan and Vernacular in History
"The Theory of Practice and the Practice of Theory in Indian Intellectual History
"Myth and Reality: Studies in the Formation of Indian Culture
"An Introduction to the Study of Indian History"
 Buffalo Nationalism: A Critique of Spiritual Fascism- Kancha Iliah Shepherd
Dispersed Radiance by Prof Abha Sur
Riddles of Hinduism Ambedkar
Buddha and his Dhamma Ambedkar
Who were the shudras Ambedkar
What Gandhi and Congress has done to untouchables Ambedkar
The untouchables, who were they and why they became untouchables Ambedkar
Buddha or Karl Marx Ambedkar
Distinction Pierre Bourdieu
Forms of capital Pierre Bourdieu
Conquest of Bread Peter Kropotkin
Dear Ijeawele, or A Feminist Manifesto in Fifteen Suggestions Chimamanda Ngozi Adichie
Feminism is for everybody Bell Hooks
We should all be feminists Chimamanda Ngozi Adichie
Sapiens Yuval Noah Hari
Mutual Aid Peter Kropotkin
Ayyankali: A Dalit Leader of Organic Protest Meena Kandasamy
Listen to my case Chandru
We also made History: Women in the Ambedkarite Movement by meenakshi moon and urmila pawar
Poisioned bread -Arjun Dangle
Strike a blow to change the world -Eknath Awad

**Comment by AnubhabRay31** [comment]
done
