### ISSUE TITLE
Complaint Tab newly had to be added

### ISSUE THREAD

**Issue by thamilthedal** [scst-cell-iitb/scst-cell-iitb#3]
<p></p>
									Your feedback is welcome. Please write to:
									<a href="mailto:scstcell[AT]iitb.ac.in" title=' replace [AT] with "@"' target="_blank">scstcell[AT]iitb.ac.in</a>, and phone: 9987466279. As mentioned above, please note: one can also
									submit an anonymous complaint online using the form:
									<a href="https://goo.gl/forms/F3BKMxkdGu28OGRz2" target="_blank" title=" complaint form">https://goo.gl/forms/F3BKMxkdGu28OGRz2</a>
									<p>
										Kindly note: the purview of the SC/ST Students Cell is limited to
										<strong>students</strong> of IIT Bombay in the context of
										discrimination about <strong>caste/race only</strong>.
										Queries/complaints outside this purview are to be directed towards the
										appropriate body and emails regarding matters outside the above
										purview are likely to be remain unanswered.

**Comment by AnubhabRay31** [comment]
done; new tab (in vertical side bar) is added. 
There is an issue of text of the contact part of the nav-panel getting hidden, no scrollability is provided so the address was getting cut off from the browser screen/window. I temporarily reduced the size of the text in the li tags to squeeze the contents in. But this is not an IDEAL solution.
Modifications appreciated... But regarding adding a new tab is done so am closing the issue.
