### ISSUE TITLE
Dismantling the myth of merit

### ISSUE THREAD

**Issue by gnaveeniit** [scst-cell-iitb/scst-cell-iitb#4]
Kindly add this content
[Dismantling the myth of Brahminical Merit (1).docx](https://github.com/scst-cell-iitb/scst-cell-iitb/files/8499539/Dismantling.the.myth.of.Brahminical.Merit.1.docx)
t

**Comment by AnubhabRay31** [comment]
Done; in resources there is a heading on this topic and a link that takes u to the blog-post.
