### ISSUE TITLE
Prohibited Casteist Slurs against SC/ST/OBC communities

### ISSUE THREAD

**Issue by gnaveeniit** [scst-cell-iitb/scst-cell-iitb#5]
Kindly add this prohibited caste/tribe slurs in campus (updated one)
[Prohibited Casteist Slurs in campus.docx](https://github.com/scst-cell-iitb/scst-cell-iitb/files/8499541/Prohibited.Casteist.Slurs.in.campus.docx)

**Comment by gnaveeniit** [comment]
Kindly make sure this is in two-column table form with first column language and second column slurs

**Comment by gnaveeniit** [comment]
The Updated One:
[Prohibited Casteist Slurs in campus.docx](https://github.com/scst-cell-iitb/scst-cell-iitb/files/8553458/Prohibited.Casteist.Slurs.in.campus.docx)

**Comment by AnubhabRay31** [comment]
Done; added the material in a table. Until further updates/additions to the list this issue stands closed.
